import { Component, Inject, Input, OnChanges, Output, EventEmitter } from "@angular/core";
import { FormControl, FormGroup, Validators } from "@angular/forms";
import {
    AJS_ANALYTICS,
    AJS_CONFIRM,
    AJS_CURRENT_USER_SERVICE,
    AJS_LOCATION,
    AJS_NAV_URLS,
    AJS_PROJECT_SERVICE,
    AJS_REPO,
    AJS_ROOT_SCOPE,
} from "../shared/ajs-tokens";
import { FormErrorMessageService } from "../shared/form-error-message.service";

/**
 * Angular replacement for the form content of the admin project-profile route
 * (app/partials/includes/modules/admin-project-profile.jade and its read-only
 * counterpart admin-project-profile-archived.jade), and for the AngularJS `tgProjectProfile`
 * directive's behaviour (app/coffee/modules/admin/project-profile.coffee) that used to sit
 * on the route's outer wrapper element with no template of its own. `ProjectProfileController`
 * itself is untouched and still owns route data-loading (`loadInitialData`) - this component
 * only replaces the checksley-validated form and the directive's submit handler; `reload`
 * calls back into `ctrl.loadInitialData()` after a successful save, same as the original's
 * `$ctrl.loadInitialData()` call (`$ctrl` was `$el.controller()`, this same controller).
 *
 * Only `name` (required, 45 chars) and `description` (required) were checksley-validated in
 * the original - everything else (looking-for-people, feedback, privacy) had no validation
 * attribute and stays a plain two-way `ngModel` binding directly on the `project` Model
 * instance (whose properties are accessor pairs generated by `Model#initialize` - see
 * app/coffee/modules/base/model.coffee - so direct mutation here is equivalent to the
 * original's `ng-model`, including marking the attribute modified for `isAttributeModified`).
 *
 * `addTag`/`deleteTag` (previously `ProjectProfileController#addTag`/`#deleteTag`, only ever
 * called from this one template) are absorbed here instead of round-tripping through the
 * controller: `project`/its tags are already a direct `@Input()`, and the derived
 * `[name, color]` tuple list `tag-line-common` needs is now a plain getter instead of a
 * separately-maintained `$scope.projectTags` array. The controller's own methods and
 * `$scope.projectTags` field were removed as dead code once this landed.
 *
 * `openDeleteLightbox` (previously on the controller too, same one-template-only situation)
 * is likewise absorbed - a direct `$rootScope.$broadcast("deletelightbox:new", project)`,
 * identical payload to the original.
 *
 * The original's `form.setErrors(data)` (per-field backend errors) is simplified to
 * surfacing `data._error_message` via `confirm.notify("error", ...)` only - same
 * simplification already used for `LightboxCreateEditComponent`; the two validated fields
 * here (name/description) essentially never fail server-side once client validation passes.
 * The `debounce 2000` double-submit guard is replaced by a plain `submitting` flag, same
 * precedent as `LightboxFeedbackComponent`.
 *
 * `projectChange` re-emits whenever the nested `<tg-project-logo>` replaces `project` with
 * a fresh Model instance (a new logo upload response) - unlike ordinary field mutation
 * (which the shared object reference already propagates to the AngularJS side for free),
 * a full object replacement needs the caller to rebind `$scope.project` itself.
 */
@Component({
    selector: "tg-admin-project-profile-form",
    templateUrl: "./admin-project-profile-form.component.html",
})
export class AdminProjectProfileFormComponent implements OnChanges {
    // Called directly from a still-AngularJS jade template (not another Angular template),
    // so these go through `downgradeComponent`'s `$attrs`-based binding rather than Angular's
    // own template compiler - see MIGRATION.md for the full binding-syntax explanation.
    // Multi-word inputs/outputs use the `bind-x`/`bindon-x`/`on-x` attribute forms in jade
    // (AngularJS's own kebab-case attribute normalization, the same mechanism `ng-click`
    // etc. rely on) rather than `[x]`/`(x)`, which this Angular version's `$attrs` handling
    // does not reliably match for multi-word names.
    @Input() project: any;
    @Input() user: any;
    @Input() canCreatePrivateProjects: any;
    @Input() activeUsers: any;
    @Input() archived = false;

    @Output() reload = new EventEmitter<void>();
    @Output() projectChange = new EventEmitter<any>();

    form = new FormGroup({
        name: new FormControl("", [Validators.required, Validators.maxLength(45)]),
        description: new FormControl("", Validators.required),
    });

    submitting = false;

    private lastPatchedProjectId: any;

    constructor(
        @Inject(AJS_REPO) private repo: any,
        @Inject(AJS_CONFIRM) private confirm: any,
        @Inject(AJS_NAV_URLS) private navUrls: any,
        @Inject(AJS_LOCATION) private location: any,
        @Inject(AJS_PROJECT_SERVICE) private projectService: any,
        @Inject(AJS_CURRENT_USER_SERVICE) private currentUserService: any,
        @Inject(AJS_ANALYTICS) private analytics: any,
        @Inject(AJS_ROOT_SCOPE) private rootScope: any,
        public errors: FormErrorMessageService,
    ) {}

    ngOnChanges(): void {
        // `project` starts as the controller's placeholder `{}` (no `id` yet) and is later
        // *replaced* (not mutated) once `loadInitialData`/a save's refetch resolves - each
        // such replacement must re-patch the form with the newly-arrived values.
        if (this.project?.id && this.project.id !== this.lastPatchedProjectId) {
            this.lastPatchedProjectId = this.project.id;
            this.form.patchValue({
                name: this.project.name,
                description: this.project.description,
            });
        }
    }

    get isOwner(): boolean {
        return this.project?.owner?.id === this.user?.id;
    }

    get projectTags(): Array<[string, string | null]> {
        if (!this.project) {
            return [];
        }

        return (this.project.tags || []).map((tag: string) => [tag, this.project.tags_colors?.[tag] ?? null]);
    }

    addTag(event: { name: string; color: string | null }): void {
        const tags = (this.project.tags || []).slice();

        if (tags.indexOf(event.name) === -1) {
            tags.push(event.name);
        }

        this.project.tags = tags;
    }

    deleteTag(event: { tag: [string, string | null] }): void {
        this.project.tags = (this.project.tags || []).filter((tag: string) => tag !== event.tag[0]);
    }

    onLogoChange(project: any): void {
        this.project = project;
        this.projectChange.emit(project);
    }

    openDeleteLightbox(): void {
        this.rootScope.$broadcast("deletelightbox:new", this.project);
    }

    submit(): void {
        if (this.submitting || this.form.invalid) {
            this.form.markAllAsTouched();
            return;
        }

        this.submitting = true;
        this.project.name = this.form.value.name;
        this.project.description = this.form.value.description;

        const privacyChanged = this.project.isAttributeModified("is_private");

        this.repo.save(this.project).then(
            () => {
                this.submitting = false;

                if (privacyChanged && this.project.is_private) {
                    this.analytics.trackEvent(
                        "project-privacy-changed",
                        "from-public-to-private",
                        "Change project privacy from public to private",
                        1,
                    );
                } else if (privacyChanged && !this.project.is_private) {
                    this.analytics.trackEvent(
                        "project-privacy-changed",
                        "from-private-to-public",
                        "Change project privacy from private to public",
                        1,
                    );
                }

                this.confirm.notify("success");

                const newUrl = this.navUrls.resolve("project-admin-project-profile-details", {
                    project: this.project.slug,
                });
                this.location.path(newUrl);

                this.projectService.fetchProject().then(() => this.reload.emit());
                this.currentUserService.loadProjects();
            },
            (data: any) => {
                this.submitting = false;

                if (data?._error_message) {
                    this.confirm.notify("error", data._error_message);
                }
            },
        );
    }
}
